### ISSUE TITLE
No module named 'ee'

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [nguyenvanthi2020/Sentinel2-Download#3]
Installation stops with this error:
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/__init__.py", line 35, in classFactory
    from .sentinel2_download import Sentinel2Download
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/sentinel2_download.py", line 33, in 
    import ee
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ee'`

**QGIS 3.10.2 on Linux Mint 19.3 (=Ubuntu 18.04)**

**Comment by nguyenvanthi2020** [comment]
Bernd-Vogelgesang, you must install the plugin named Google Earth Engine before install this.

Cheers,

**Comment by Bernd-Vogelgesang** [comment]
Ah, did not know this.
Unfortunately, this does not work as well.
```
Couldn't load plugin 'ee_plugin' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'StringIO' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 25, in classFactory
    from .ee_plugin import GoogleEarthEnginePlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/ee_plugin.py", line 22, in 
    import ee
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bernd/.local/lib/python3.6/site-packages/ee/__init__.py", line 1, in 
    from .main import main
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bernd/.local/lib/python3.6/site-packages/ee/main.py", line 10, in 
    import StringIO
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'StringIO'

```

**Comment by nguyenvanthi2020** [comment]
This error relevant to Google Earth Engine plugin, so you can find help here: https://github.com/gee-community/qgis-earthengine-plugin/issues

Cheers,
