### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'ee_plugin'


### ISSUE THREAD

**Issue by baditaflorin** [nguyenvanthi2020/Sentinel2-Download#6]
Couldn't load plugin 'sentinel2_download' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/__init__.py", line 12, in classFactory
    from .Sentinel2_Download_Menu import s2_menu
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Menu.py", line 4, in <module>
    from .Sentinel2_Download_Dialog import *
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Dialog.py", line 6, in <module>
    from .Sentinel2_Download_Library import *
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Library.py", line 7, in <module>
    from ee_plugin import Map
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ee_plugin'

```
sentinel2_download 3.1, QGIS 3.4.5-Madeira on Darwin 19.6.0

**Comment by mikedufty** [comment]
Do you have the Google Earth Engine plugin installed and working?  It is a pre-requisite for the sentinel download plug in to work.  It needs a log in with a google account too.

**Comment by Melagiris** [comment]
> Do you have the Google Earth Engine plugin installed and working? It is a pre-requisite for the sentinel download plug in to work. It needs a log in with a google account too.


Can you please provide steps to do the following, as I am too facing the same issue?

**Comment by mikedufty** [comment]
It looks like the earthengine plugin is having some issues.  If you look at it's github pages there is some discussion.
This causes issues with the automatic authentication.
The current version of the plugin works fine once authenticated, but it fails with an error if not authenticated, instead of opening web pages to get authentication as it is supposed to.

What I found worked for me was.
1. IN QGIS go to plugins, manage and install plugins, settings, and tick "show also experimental plugins"
2. Go to the google earth engine plugin, and choose upgrade experimental plugin.
3. The experimental version authentication seems to work - follow the prompts, login with your google account, copy the authentication code and paste as directed.  (you may need to sign up for google earth engine on the google earth engine page first, not sure as I already had).
4. Now the google earth engine plugin will, work, but sentinel downloader won't.  You need to downgrade back to the non-experimental google earth engine plugin, in the QGIS plugin manager.
5. I had to restart QGIS after doing this - then it worked.  

If this works for anyone else can you let us know here.
